### PR TITLE
Implement Rogue Event

### PR DESCRIPTION
**Pull request by ghost**
## In this PR
- Rewrite and Fix Rogue Event
- Upload some gold and gears proto

## Known Issue
- Player may meet dev events
- Some type cannot be handled / handled correctly

## Why WIP
Maybe I will implement gold and gears, but I'm lazy XD

### CODE REVIEW

**Comment by ghost** [comment]
No longer WIP
becuz im too lazy to implement gold and gears lol

**Comment by Melledy** [comment]
Much appreciated, I will look over it when I have time to later.

**Comment by Hiro420** [comment]
Might need to deobfuscate the protos, may you send the .proto files you used?

**Comment by ghost** [comment]
> Might need to deobfuscate the protos, may you send the .proto files you used?

i dm u

**Pull request merged**
