### PR TITLE
Fix pet & kick

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by letheriver2007** [comment]
Sincerely waiting for unban me from your discord server, my acc name is "letheriver2007".
(my account was hacked by a bot former)

**Comment by letheriver2007** [comment]
A little mistake, the proto is for 2.5

**Review by Hiro420 — CHANGES_REQUESTED** [review]
Please change proto version to 2.4 💀

**Comment by letheriver2007** [comment]
> Please change proto version to 2.4 💀

ok
(I had deleted 235 dumped protos......

**Comment by letheriver2007** [comment]
> Please change proto version to 2.4 💀

syntax = "proto3";

option java_package = "emu.lunarcore.proto";

import "BlackInfo.proto";

message PlayerKickOutScNotify {
    KickType kick_type = 12;
    enum KickType {
        KICK_SQUEEZED = 0;
        KICK_BLACK = 1;
        KICK_CHANGE_PWD = 2;
        KICK_LOGIN_WHITE_TIMEOUT = 3;
        KICK_ACE_ANTI_CHEATER = 4;
        KICK_BY_GM = 5;
    }
	BlackInfo black_info = 5;
}

**Comment by ghost** [comment]
> Please change proto version to 2.4 💀

Okay now, i have already fix that.
(Hiro bro kisskiss

**Comment by ghost** [comment]
@Hiro420

**Comment by Hiro420** [comment]
make it in a new commit

**Pull request closed without merging**
