### PR TITLE
Add Readme_id-ID

### PR DESCRIPTION
**Pull request by Adekjamannow**
I want you to add the Indonesian version of "Readme".

### CODE REVIEW

**Comment by Melledy** [comment]
Please undo your changes in `GachaService.java`

**Comment by Adekjamannow** [comment]
> Please undo your changes in `GachaService.java`

Done

**Comment by Melledy** [comment]
Revert `purpleAvatars` too in `GachaService.java`

**Comment by Adekjamannow** [comment]
> Revert `purpleAvatars` too in `GachaService.java`

Ah, my bad, done

**Pull request merged**
